window.PRODUCTS = [
  {
    id: 1024,
    category: "ring",
    title: { ru: "Модель 1024", ro: "Model 1024" },
    type: { ru: "Кольцо", ro: "Inel" },
    material: { ru: "розовое золото 585", ro: "aur roz 585" },
    stones: { ru: "с бриллиантами", ro: "cu diamante" },
    price: 5850,
    visual: "ring rose",
    popular: 9,
  },
  {
    id: 2057,
    category: "ring",
    title: { ru: "Модель 2057", ro: "Model 2057" },
    type: { ru: "Кольцо", ro: "Inel" },
    material: { ru: "белое золото 585", ro: "aur alb 585" },
    stones: { ru: "с бриллиантом", ro: "cu diamant" },
    price: 6100,
    visual: "ring silver",
    popular: 8,
  },
  {
    id: 3011,
    category: "signet",
    title: { ru: "Модель 3011", ro: "Model 3011" },
    type: { ru: "Печатка", ro: "Inel barbatesc" },
    material: { ru: "жёлтое золото 585", ro: "aur galben 585" },
    stones: { ru: "с ониксом", ro: "cu onix" },
    price: 7200,
    visual: "signet gold",
    popular: 10,
  },
  {
    id: 4008,
    category: "pendant",
    title: { ru: "Модель 4008", ro: "Model 4008" },
    type: { ru: "Подвеска", ro: "Pandantiv" },
    material: { ru: "белое золото 585", ro: "aur alb 585" },
    stones: { ru: "с бриллиантами", ro: "cu diamante" },
    price: 2950,
    visual: "pendant silver",
    popular: 7,
  },
  {
    id: 5012,
    category: "earrings",
    title: { ru: "Модель 5012", ro: "Model 5012" },
    type: { ru: "Серьги", ro: "Cercei" },
    material: { ru: "розовое золото 585", ro: "aur roz 585" },
    stones: { ru: "с фианитами", ro: "cu zirconii" },
    price: 4450,
    visual: "earrings rose",
    popular: 6,
  },
  {
    id: 6003,
    category: "bracelet",
    title: { ru: "Модель 6003", ro: "Model 6003" },
    type: { ru: "Браслет", ro: "Bratara" },
    material: { ru: "жёлтое золото 585", ro: "aur galben 585" },
    stones: { ru: "византийское плетение", ro: "impletitura bizantina" },
    price: 6750,
    visual: "bracelet gold",
    popular: 8,
  },
  {
    id: 1033,
    category: "exclusive",
    title: { ru: "Модель 1033", ro: "Model 1033" },
    type: { ru: "Эксклюзивное кольцо", ro: "Inel exclusiv" },
    material: { ru: "платина 950", ro: "platina 950" },
    stones: { ru: "с бриллиантами", ro: "cu diamante" },
    price: 12600,
    visual: "ring silver",
    popular: 10,
  },
  {
    id: 5021,
    category: "earrings",
    title: { ru: "Модель 5021", ro: "Model 5021" },
    type: { ru: "Серьги", ro: "Cercei" },
    material: { ru: "белое золото 585", ro: "aur alb 585" },
    stones: { ru: "с бриллиантами", ro: "cu diamante" },
    price: 3650,
    visual: "earrings silver",
    popular: 7,
  },
  {
    id: 7108,
    category: "chain",
    title: { ru: "Модель 7108", ro: "Model 7108" },
    type: { ru: "Цепь", ro: "Lant" },
    material: { ru: "жёлтое золото 585", ro: "aur galben 585" },
    stones: { ru: "якорное плетение", ro: "impletitura ancora" },
    price: 5300,
    visual: "chain gold",
    popular: 5,
  },
  {
    id: 8114,
    category: "cross",
    title: { ru: "Модель 8114", ro: "Model 8114" },
    type: { ru: "Крестик", ro: "Cruce" },
    material: { ru: "белое золото 585", ro: "aur alb 585" },
    stones: { ru: "с гравировкой", ro: "cu gravura" },
    price: 2400,
    visual: "cross silver",
    popular: 6,
  },
  {
    id: 8120,
    category: "cross",
    title: { ru: "Модель 8120", ro: "Model 8120" },
    type: { ru: "Иконка", ro: "Iconita" },
    material: { ru: "жёлтое золото 585", ro: "aur galben 585" },
    stones: { ru: "ручная доработка", ro: "finisaj manual" },
    price: 3800,
    visual: "pendant gold",
    popular: 5,
  },
  {
    id: 9302,
    category: "exclusive",
    title: { ru: "Модель 9302", ro: "Model 9302" },
    type: { ru: "Авторский комплект", ro: "Set exclusiv" },
    material: { ru: "комбинированное золото", ro: "aur combinat" },
    stones: { ru: "с сапфирами", ro: "cu safire" },
    price: 14800,
    visual: "ring gold",
    popular: 9,
  },
];
